server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public;


    # Serveur principal
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Fichiers statiques (assets)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
    }

    # Refuser l'accès aux fichiers cachés
    location ~ /\. {
        deny all;
    }

    # Refuser l'accès aux fichiers .env
    location ~ /\.env {
        deny all;
    }
}
